---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
## Descriptive Statistics of Variables


### Libraries & Datasets
```{r warning=FALSE}

library(readxl)
library(dplyr)
library(ggplot2)

df_2010 <- read_excel("data_2010.xlsx")

barfill <- "#4271AE"
barlines <- "#1F3552"

```


### Starting with 2000 Model 

### Dependent Variables
```{r}

summary(df_2010$causality_log)
sd(df_2010$causality_log)

ggplot(df_2010, aes(x = causality_log)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.1,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Casualty (log)") +
  theme_classic()




summary(df_2010$prop_dmg_log)
sd(df_2010$prop_dmg_log)

ggplot(df_2010, aes(x = prop_dmg_log)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.1,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Property Damage (log)") +
  theme_classic()

```



### Social Dimension
```{r social}


## african american or black

summary(df_2010$per_black)
sd(df_2010$per_black)

p1 <- ggplot(df_2010, aes(x = per_black)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.02,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("African American or Black Population by County") +
  theme_classic()

p1

## asian
summary(df_2010$per_asian)
sd(df_2010$per_asian)

p2 <- ggplot(df_2010, aes(x = per_asian)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.01,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Asian Population by County") +
  theme_classic()

p2

## elderly
summary(df_2010$per_elderly)
sd(df_2010$per_elderly)

p3 <- ggplot(df_2010, aes(x = per_elderly)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.01,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Elderly Population by County") +
  theme_classic()

p3

## yound dependent 
summary(df_2010$per_young_dependent)
sd(df_2010$per_young_dependent)

p4 <- ggplot(df_2010, aes(x = per_young_dependent)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.002,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Young Dependent by County") +
  theme_classic()

p4

## foreigner born
summary(df_2010$per_foreign_born)
sd(df_2010$per_foreign_born)

p5 <- ggplot(df_2010, aes(x = per_foreign_born)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.005,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Foreign Born by County") +
  theme_classic()

p5


## female hh w children under 6
summary(df_2010$per_female_hh_with_kids_under6)
sd(df_2010$per_female_hh_with_kids_under6)

p6 <- ggplot(df_2010, aes(x = per_female_hh_with_kids_under6)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.002,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Female Household with Children under 6 by County") +
  theme_classic()

p6

# rural
summary(df_2010$per_rural)
sd(df_2010$per_rural)

p7 <- ggplot(df_2010, aes(x = per_rural)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.01,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Proportion of Percentange Rural Population by County") +
  theme_classic()

p7

## american indian
summary(df_2010$per_american_indian)
sd(df_2010$per_american_indian)

p7 <- ggplot(df_2010, aes(x =per_american_indian )) +
        geom_histogram(aes(y = ..count..), binwidth = 0.01,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("American Indian and Alaska Native Population by County") +
  theme_classic()

p7


## Less than high-school
summary(df_2010$per_no_school_completed)
sd(df_2010$per_no_school_completed)

p8 <- ggplot(df_2010, aes(x = per_no_school_completed)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.001,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("No School Completed Population by County") +
  theme_classic()

p8

```

### Economic Dimension
```{r economic}
## median hh income (US$)

summary(df_2010$median_hh_income_2010)
sd(df_2010$median_hh_income_2010)

pe1 <- ggplot(df_2010, aes(x = median_hh_income_2010)) +
        geom_histogram(aes(y = ..count..), binwidth = 1000,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "US$")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Median Household Income (US$) by County") +
  theme_classic()

pe1


## renter
summary(df_2010$per_rent)
sd(df_2010$per_rent)

pe2 <- ggplot(df_2010, aes(x = per_rent)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.01,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Proportion of Percentange Renter Population by County") +
  theme_classic()

pe2


## Average hh size
summary(df_2010$average_hh)
sd(df_2010$average_hh)

pe3 <- ggplot(df_2010, aes(x = average_hh)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.05,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "number")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Average Household Size by County") +
  theme_classic()

pe3

## college or higher education
summary(df_2010$per_college_or_higher)
sd(df_2010$per_college_or_higher)

pe4 <- ggplot(df_2010, aes(x = per_college_or_higher)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.01,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("College or Higher Population by County") +
  theme_classic()

pe4

## hh with lack of plumbing
summary(df_2010$per_lack_plumbing)
sd(df_2010$per_lack_plumbing)

pe5 <- ggplot(df_2010, aes(x = per_lack_plumbing)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.005,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("ack of Plumbing Household  by County") +
  theme_classic()

pe5

## unemployment
summary(df_2010$per_unemployed)
sd(df_2010$per_unemployed)

pe6 <- ggplot(df_2010, aes(x = per_unemployed)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.005,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Unemployed Population by County") +
  theme_classic()

pe6


```

### Health Dimension
```{r}
## Diabetes


summary(df_2010$diabetes_2010)
sd(df_2010$diabetes_2010)

ph1 <- ggplot(df_2010, aes(x = diabetes_2010)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.5,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Diabetes Population") +
  theme_classic()

ph1


## nursing home
summary(df_2010$per_nursing)
sd(df_2010$per_nursing)

ph2 <- ggplot(df_2010, aes(x = per_nursing)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.02,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "proportion of percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Nursing Home Population") +
  theme_classic()

ph2

```


### institutional dimension
```{r}

## fema 
summary(df_2010$FEMA_total)
sd(df_2010$FEMA_total)

pi1 <- ggplot(df_2010, aes(x = FEMA_total)) +
        geom_histogram(aes(y = ..count..), binwidth = 20000000,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "US$")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Fema Disaster Aid") +
  theme_classic()

pi1
## research institution
summary(df_2010$number_research_institutions)
sd(df_2010$number_research_institutions)

pi2 <- ggplot(df_2010, aes(x = number_research_institutions)) +
        geom_histogram(aes(y = ..count..), binwidth = 1,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "number")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Research Institutions") +
  theme_classic()

pi2
# numb of local government employees
summary(df_2010$employees_2001)
sd(df_2010$employees_2001)

pi3 <- ggplot(df_2010, aes(x = employees_2001)) +
        geom_histogram(aes(y = ..count..), binwidth = 3000,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "number")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Local Government Employees") +
  theme_classic()

pi3
```


### environmental dimension
```{r}
#air quality

summary(df_2010$air_quality)
sd(df_2010$air_quality)

pen1 <- ggplot(df_2010, aes(x = air_quality)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.1,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "index value")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Air Quality") +
  theme_classic()

pen1



#built quality
summary(df_2010$built_quality)
sd(df_2010$built_quality)

pen3 <- ggplot(df_2010, aes(x = built_quality)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.1,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "index value")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Built Quaity") +
  theme_classic()

pen3

# land quality
summary(df_2010$land_quality)
sd(df_2010$land_quality)

pen4 <- ggplot(df_2010, aes(x = land_quality)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.1,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "index value")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Land Quality") +
  theme_classic()

pen4

# impervious surface

summary(df_2010$impervious_surface)
sd(df_2010$impervious_surface)

pen5 <- ggplot(df_2010, aes(x = impervious_surface)) +
        geom_histogram(aes(y = ..count..), binwidth = 0.5,
                       colour = barlines, fill = barfill) +
        scale_x_continuous(name = "percentage")+
        scale_y_continuous(name = "Frequency") +
        ggtitle("Impervious Surface") +
  theme_classic()

pen5
```

